#!/bin/bash

declare -A phases
phases=(
    [lexer]="--lexfuzz"
    [parser]="--parsefuzz"
    [semantics]="--fuzz-check"
)

for x in "${!phases[@]}"; do
    [[ ${1} == ${x} ]] && valid_arg=1
done

[[ ${#} -eq 1 && ${valid_arg} == 1 ]] || { echo "pass one of: ${!phases[@]}"; exit 1; }

afl_args=(
    -i -
    -o artifacts/afl
    -x mj_parser.dict
    -M fuzz_1
    ../builddir/fuzzing/afl_fuzzer/mjc_instr
    ${phases[${1}]}
    @@
)

cd ${0%/*}
afl_fuzzer/afl/afl-fuzz "${afl_args[@]}"

