#!/bin/bash

declare -A phases
phases=(
    [lexer]="--lexfuzz"
    [parser]="--parsefuzz"
    [semantics]="--fuzz-check"
)

for x in "${!phases[@]}"; do
    [[ ${1} == ${x} ]] && valid_arg=1
done

[[ ${#} -eq 1 && ${valid_arg} == 1 ]] || { echo "pass one of: ${!phases[@]}"; exit 1; }

cd ${0%/*}

output_dir="artifacts/afl"
work_dir="fuzz_0"
lock_dir=.${work_dir}.lock

# lock our work dir. Works because mkdir is atomic and fails if the dir exists
if ! mkdir "${output_dir}/${lock_dir}"; then
    echo "couldn't lock output dir, maybe you want to run a slave instance?"
    exit 2
fi

afl_args=(
    -i -
    -o "${output_dir}"
    -x mj_parser.dict
    -M "${work_dir}"
    ../builddir/fuzzing/afl_fuzzer/mjc_instr
    "${phases[${1}]}"
    @@
)

afl_fuzzer/afl/afl-fuzz "${afl_args[@]}"

# unlock
rmdir "${output_dir}/${lock_dir}"

