#!/bin/sh
# make -j5 -C llvm_fuzzer/build && ASAN_OPTIONS=coverage=1 ./llvm_fuzzer/build/fuzzmjc corpus/lexer/ -artifact_prefix=artifacts/llvm/ -dict=mj_lexer.dict -jobs=8
# make -j5 -C llvm_fuzzer/build && ASAN_OPTIONS=coverage=1 ./llvm_fuzzer/build/fuzzmjc corpus/parser/ -artifact_prefix=artifacts/llvm/ -dict=mj_parser.dict -jobs=8
# make -j5 -C llvm_fuzzer/build && ASAN_OPTIONS=coverage=1 ./llvm_fuzzer/build/fuzzmjc corpus/semantics/ -artifact_prefix=artifacts/llvm/ -dict=mj_parser.dict -jobs=8

corpus=corpus/lexer/
corpus=corpus/parser/
corpus=corpus/semantics/

fuzzer_args=(
    ${corpus}
    -artifact_prefix=artifacts/llvm/
    -dict=mj_parser.dict
    -jobs=8
)

cd "${0%/*}"
ASAN_OPTIONS=coverage=1 ../builddir/fuzzing/llvm_fuzzer/fuzzmjc "${fuzzer_args[@]}"
