#!/bin/bash
if [[ $UID -ne 0 ]]; then
  echo Error, needs to be run as root
  exit 1
fi

echo core >/proc/sys/kernel/core_pattern
cd /sys/devices/system/cpu
echo performance | tee cpu*/cpufreq/scaling_governor
