#!/bin/sh

scriptpath=$(readlink -f "${0}")
basedir=$(dirname "${scriptpath}")
builddir=${basedir}/builddir


edo() {
    [ -z ${DEBUG_SCRIPTS} ] || echo "${@}"
    "${@}" || exit 100
}

_check() {
    edo make -j -C "${builddir}" CTEST_PARALLEL_LEVEL=12 check "${@}"
}

_main() {
    _check "${@}"
}

_main "${@}"
