#!/bin/sh

scriptpath=$(readlink -f "${0}")
basedir=$(dirname "${scriptpath}")
builddir=${basedir}/builddir

compilername=mjc
compilerpath=${builddir}/${compilername}


edo() {
    echo "${@}"
    "${@}" || exit 100
}

_run() {
    edo "${compilerpath}" "${@}"
}

_main() {
    _run "${@}"
}

_main "${@}"
